version: '3.4'

services:
  db:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Services/WebStore.WebAPI/Dockerfile

  webstore:
    image: ${DOCKER_REGISTRY-}webstore
    build:
      context: .
      dockerfile: UI/WebStore/Dockerfile
